baseurl = "https://hun0691.github.io/"
title = "Read, Write, Memory"

languageCode = "ko-KR"
DefaultContentLanguage = "kr"
theme = "hugo-hello-programmer-theme"
disqusShortname = "XXXX"
googleAnalytics = "UA-XXXXXXXX-X"
paginate = 7

[author]
    name = "JungHOON"
    email = "test"

[params]
    description = "desribe-your-site"
